[archiso-systemd-boot]
source = "regex"
url = "https://archlinux.org/download/"
regex = "Current Release:</strong> ([0-9.]+)"

[visual-studio-code-bin]
source = "cmd"
cmd = "curl -s https://update.code.visualstudio.com/api/releases/stable | jq -r '.[0]'"

[slack-desktop]
source = "regex"
url = "https://slack.com/release-notes/linux"
regex = "Slack ([0-9]+\\.[0-9]+\\.[0-9]+)"

[plex-media-server-plexpass]
source = "cmd"
cmd = "curl -s 'https://plex.tv/api/downloads/5.json?channel=plexpass' | jq -r '.computer.Linux.version'"

[plex-htpc]
source = "cmd"
cmd = "curl -s -H 'Snap-Device-Series: 16' https://api.snapcraft.io/v2/snaps/info/plex-htpc | jq -r 'first(.\"channel-map\"[] | select(.channel.name==\"stable\").version)'"

[metapac]
source = "cratesio"
cratesio = "metapac"

[helm-docs]
source = "github"
github = "norwoodj/helm-docs"
include_regex = "[0-9.]+"
use_latest_release = true
prefix = "v"

[tuxedo-control-center-bin]
source = "rpmrepo"
repo = "https://rpm.tuxedocomputers.com/fedora/43/x86_64/base/"
pkg = "tuxedo-control-center"
arch = "x86_64"

[tuxedo-drivers-dkms]
source = "git"
git = "https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers.git"
include_regex = "v[0-9.]+"
prefix = "v"

[synology-drive]
source = "regex"
url = "https://archive.synology.com/download/Utility/SynologyDriveClient"
regex = "SynologyDriveClient/([0-9]+\\.[0-9]+\\.[0-9]+-[0-9]+)"
from_pattern = "-"
to_pattern = "_"

[yay]
source = "github"
github = "Jguer/yay"
include_regex = "v[0-9.]+"
use_max_tag = true
prefix = "v"

[zwait]
source = "github"
github = "ironashram/zwait"
include_regex = "v[0-9.]+"
use_max_tag = true
prefix = "v"

[openconnect-fortinet-saml]
source = "github"
github = "ironashram/openconnect-fortinet-saml"
include_regex = "v[0-9.]+"
use_max_tag = true
prefix = "v"
